meta_name: "Event Buddy"
meta_title: "Event Buddy - Events are better with friends"
meta_description: "The social app that connects you with events and like-minded people to attend them with. With Event Buddy, you can discover new events in your area, find people who share your interests, and plan outings together. Whether you're looking for someone to attend a concert or party, try a new restaurant,go to a museum or exhibition, or just explore a new city with, Event Buddy has got you covered."
meta_image: "cover.png" # should exist in `app/assets/images/`
